[[resource_sync]]
name = "base_helper"
[resource_sync.config]
repo = "Myrenic/WyvernWatch"
resource_path = ["./toml/base_helper.toml"]
include_variables = true

[[repo]]
name = "Myrenic/WyvernWatch"
[repo.config]
server = "Local"
builder = "Local"
repo = "Myrenic/WyvernWatch"