[[resource_sync]]
name = "base"
[resource_sync.config]
repo = "Myrenic/WyvernWatch"
resource_path = [
  "./toml/base.toml",
  "./toml/general/"
]
include_variables = true

[[repo]]
name = "Myrenic/WyvernWatch"
[repo.config]
server = "Local"
builder = "Local"
repo = "Myrenic/WyvernWatch"