[[stack]]
name = "zabbix-proxy"
[stack.config]
server = "Local"
poll_for_updates = true
auto_update = true
repo = "Myrenic/WyvernWatch"
run_directory = "./apps/zabbix-proxy/"
environment = """
MYSQL_DATABASE=zabbix_proxy
MYSQL_USER=[[ZABBIX_PROXY_MYSQL_USER]]
MYSQL_PASSWORD=[[ZABBIX_PROXY_MYSQL_PASSWORD]]
MYSQL_ROOT_PASSWORD=[[ZABBIX_PROXY_MYSQL_ROOT_PASSWORD]]
ZBX_SERVER_HOST=[[ZABBIX_PROXY_ZBX_SERVER_HOST]]
ZBX_SERVER_PORT=10051
ZBX_HOSTNAME=[[ZABBIX_PROXY_ZBX_HOSTNAME]]
ZBX_PROXYMODE=0
ZBX_CACHESIZE=256M
ZBX_HISTORYCACHESIZE=128M
ZBX_HISTORYINDEXCACHESIZE=32M
ZBX_STARTPOLLERS=50
ZBX_STARTSNMPPOLLERS=20
ZBX_STARTPREPROCESSORS=20
ZBX_STARTTRAPPERS=20
DB_SERVER_HOST=mysql
ZBX_TLSPSKFILE=[[ZABBIX_PROXY_ZBX_TLSPSKFILE]]
"""