[[stack]]
name = "zabbix"
[stack.config]
server = "Local"
poll_for_updates = true
auto_update = true
repo = "Myrenic/WyvernWatch"
run_directory = "./apps/zabbix/"
environment = """
DB_SERVER_HOST=zabbix-db
ZBX_LOG_LEVEL=4
POSTGRES_DB=zabbix
POSTGRES_USER=zabbix
POSTGRES_PASSWORD=[[POSTGRES_PASSWORD]]
ZBX_CACHESIZE=2G
ZBX_HISTORYCACHESIZE=1G
ZBX_TRENDCACHESIZE=512M
ZBX_VALUECACHESIZE=512M
ZBX_STARTPOLLERS=200
ZBX_STARTIPMIPOLLERS=10
ZBX_STARTPOLLERSUNREACHABLE=40
ZBX_STARTTRAPPERS=100
ZBX_STARTPINGERS=40
ZBX_STARTVMWARECOLLECTORS=5
ZBX_STARTDISCOVERERS=30
ZBX_STARTHTTPPOLLERS=30
ZBX_STARTTIMERS=30
ZBX_STARTESCALATORS=30
ZBX_STARTALERTERS=30
ZBX_TIMEOUT=30
ZBX_LOGSLOWQUERIES=3000
ZBX_STARTDBSYNCERS=16
ZBX_HOUSEKEEPINGFREQUENCY=1
ZBX_MAXHOUSEKEEPERDELETE=50000
ZBX_NODEADDRESS=[[ZBX_NODEADDRESS]]
ZBX_HANODENAME=[[ZBX_HANODENAME]]
ZBX_SERVER_NAME=[[ZBX_SERVER_NAME]]
PHP_TZ=[[PHP_TZ]]
ZBX_SSO_IDP_CERT=/certs/Azure.cer
ZBX_SSO_SETTINGS=[[ZBX_SSO_SETTINGS]]
"""